name: client

type: nodejs:14

build:
  # We set flavor to none in order to use yarn.
  # https://docs.platform.sh/languages/nodejs.html#use-yarn-as-a-package-manager
  flavor: none

dependencies:
  nodejs:
    # Latest yarn.
    yarn: "*"

# The configuration of app when it is exposed to the web.
web:
  locations:
      "/client":
          root: "display-client/build"
          # Default to serve our static index
          index: ['index.html']
          # No not allow any scripts
          scripts: false
          # Any misses should go to index.html which will result in React
          # handling the request
          passthru: "/client/index.html"

# Build the react app and copy/render any templates that will be needed by
# the app at runtime.
hooks:
  build: |
    set -e
    export DEPLOY_VERSION="$(tr '\n' ' ' < display-revision.txt)"
    export DEPLOY_TIMESTAMP="$(date)"
    cd display-client
    yarn install
    PUBLIC_URL=/client yarn build
    cp ../config-templates/template-config.json build/config.json
    envsubst '$DEPLOY_VERSION $DEPLOY_TIMESTAMP' < ../config-templates/template-release.json > build/release.json
