name: admin

source:
    root: /apps/admin

type: nodejs:14

build:
  # We set flavor to none in order to use yarn.
  # https://docs.platform.sh/languages/nodejs.html#use-yarn-as-a-package-manager
  flavor: none

dependencies:
  nodejs:
    # Latest yarn.
    yarn: "*"

# The configuration of app when it is exposed to the web.
web:
  commands:
    start: sleep infinity
  locations:
      "/admin":
          root: "display-admin-client/build"
          index: ['index.html']
          scripts: false
          passthru: "/index.html"
          allow: true

# The hooks that will be performed when the package is deployed.
hooks:
  build: |
    set -e
    echo "building"
    cd display-admin-client
    yarn install
    PUBLIC_URL=/admin yarn build
    cp ../config-template/template-config.json build/config.json
    cp ../config-template/template-access-config.json build/access-config.json
    curl -sS https://platform.sh/cli/installer | php

